### ISSUE TITLE
Missing module

### ISSUE THREAD

**Issue by EndingCredits** [SonyCSL-Paris/DeepBach#1]
`h5py` is a required module but isn't included in `requirements.txt`. I am using Theano on CentOS with python3.4. Manually installing it with pip3 worked fine.

I also get an error:
```
    timesteps = int(models[0].input[0]._shape[1])
AttributeError: 'TensorVariable' object has no attribute '_shape'
```
I'm presuming this is a problem with the theano versus tensorflow backend. I wasn't able to find a workaround, although setting this to 0 seemed to make everything run.

And don't forget to add a link to the paper to `README.txt`! Haven't had a chance to really dig into it yet, but the results I listened to were great!

EDIT: Any chance of instructions on how to train on alternative datasets?

**Comment by Ghadjeres** [comment]
Thanks for your remarks.
It was indeed a problem with the theano backend. It is fixed. I also added the h5py requirement.

For an alternative dataset, for the moment, you can for instance create another dataset running data_utils.py:
if you change 
 `chorale_list = filter_file_list(corpus.getBachChorales(fileExtensions='xml'))`
by
 `chorale_list = filter_file_list(corpus.getMonteverdiMadrigals(fileExtensions='xml'))`

and set variables 
* `NUM_VOICES` to the correct number of voices
* `RAW_DATASET` to the location where to store your dataset


If you already have a dataset, you must pickle it and set `RAW_DATASET` to the location of your pickle file. It must be a tuple
`(X, min_pitches, max_pitches, num_voices)`
where X is list of numpy arrays of shape `(num_voices, time, 3)`, _one for each musical piece_
min_pitches and max_pitches are lists containing the min (or max) pitch for each voice.
`X[0][0, 0, :]` is a list containing of the form [pitch, articulation (if the note is played or held), fermata (if the note is under a fermata symbol)]
