### ISSUE TITLE
Running on Mac OS 10.12.2 error

### ISSUE THREAD

**Issue by rzil** [SonyCSL-Paris/DeepBach#3]
I followed the installation instructions in the Readme. When I run the following command
python3 deepBach.py -l 100
I get this error

FSPathMakeRef(/Applications/Finale Notepad 2014.app) failed with error -43.

Please help.

**Comment by Ghadjeres** [comment]
Have you tried changing the editor called by music21 with MuseScore?
You can also add the "-o path/to/output/file" command to export to midi and then open it with preferred editor.

**Comment by rzil** [comment]
The -o option works for my purposes.
