### ISSUE TITLE
'Chord' object has no attribute 'pitch'

### ISSUE THREAD

**Issue by King-of-Limbs** [SonyCSL-Paris/DeepBach#4]
I was able  to process the included "God Save the Queen" sample (by running python3 deepBach.py -l 100). But when I try to run DeepBach with another midi (from musescore) I get an: AttributeError: 'Chord' object has no attribute 'pitch'

What's the problem with those?

And thanks for the great work on this one btw. :)

**Comment by Ghadjeres** [comment]
Your midi file must be monophonic, otherwise you get a Chord object instead of a Note object when parsing your file

**Comment by King-of-Limbs** [comment]
I see! I thought that God save the Queen midi in the repository to be the source not the processed file (by only looking on but not listening to it) and assumed polyphonic midis would work fine. Thanks monophonic ones work.
